### ISSUE TITLE
Very, very cool!

### ISSUE THREAD

**Issue by Noemata** [mwong510ca/HeuristicSearch-AdditivePatternDatabase-15Puzzle#1]
I'm in the process of developing a 15 puzzle game for Windows UWP.  I'd like to use the solution you have presented here.  I will have to write this in C# and would appreciate some guidance in porting over the code.  I presently have most of the GUI game play done.

If you are interested, the port could be done collaboratively and you could then roll it into your repository here.  I'm also curious about any ideas you have around compressing the database.  My game will be downloaded through the Windows Store and a 130MB download is rather steep for some regions in the world.

**Comment by mwong510ca** [comment]
I just compress the runnable version for easy download and skip the generation time.  
After unzip, it takes about 613MB.  The pattern database 7-8 takes about 576MB.  1 byte per pattern, I don't think I can reduce the size.
