### ISSUE TITLE
Such a good program!

### ISSUE THREAD

**Issue by cpuu** [mwong510ca/HeuristicSearch-AdditivePatternDatabase-15Puzzle#2]
Good morning!
I'm making the sliding puzzle solver.
This article has been a great help to me.

When I try to solve 5 by 5 problems, not 4 by 4,
If I can modify this source code, how do I solve it? 
Do I have to build a new pattern database for 5 by 5 puzzle? 
Could you advise me?
Very Thaks!

**Comment by mwong510ca** [comment]
You have redo the pattern database for 5 by 5, and walking distance won't work on 5 by 5.  See attachment page 292.  

https://www.aaai.org/Papers/JAIR/Vol22/JAIR-2209.pdf
